config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :users 
 resources :recipes  do
 resources :recipe_foods
 end
 resources :foods  
 resources :inventories


 get 'home', to: 'static#home'


  # Defines the root path route ("/")

   root "static#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  # belongs_to :user
  has_many :inventory_foods, foreign_key: 'food_id'
  has_many :recipe_foods, foreign_key: 'food_id'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  # belongs_to :user
  has_many :inventory_foods, foreign_key: 'inventory_id'
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  def get_ingredient(recipe)
    ingredient= []
    recipe_foods = RecipeFood.where(recipe_id: recipe)

    recipe_foods.each do |recipe_food|
      Food.where(id: recipe_food.food_id).each do |food|
        ingredient.push(food)
      end
    end
    ingredient
  end


 
  
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, foreign_key: 'user_id'
   has_many :inventories, foreign_key: 'user_id'
   has_many :recipes, foreign_key: 'user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(name: food_params[:name], price: food_params[:price],
                     measurement_unit: food_params[:measurement_unit])
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy!
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/inventory_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(name: inventory_params[:name])
    if @inventory.valid? && @inventory.save
      redirect_to inventory_path
    else
      render :new
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy!
    redirect_to inventory_path
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
    def index
   @foods = Food.all
    end
    def show
    end
    def new 
      @foods = Food.all
      @user = current_user
      @recipe = Recipe.find_by_id(params[:recipe_id])
      # @available_food = @user.foods
      @recipe_food = RecipeFood.new
    end
    def destroy
    end
    def create
      @recipe = Recipe.find(params[:recipe_id])
        @ingredient = @recipe.recipe_foods.new(quantity: recipe_food_params[:quantity], food_id: recipe_food_params[:food_id])
        if @ingredient.valid? && @ingredient.save
            redirect_to recipe_path(@recipe.id)
          else
            render :new
          end
    end
    private
    def recipe_food_params
        params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
    end
  end
  

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    # @ingredients = Recipe.get_ingredient(@recipe)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params.merge(user_id: current_user.id))
    if @recipe.valid? && @recipe.save
      redirect_to user_recipes_path
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy!
    redirect_to user_recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @user = current_user
     end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<h1>Foods</h1>

<button><%= link_to ("Add food"), new_food_path%></button>
<%@foods.each do |food|%>

<table>
<tr>
  <th>Food</th>
  <th>Measurement Unit</th>
  <th>Unit Price</th>
  <th>Actions</th>
</tr>
<tr>
  <td> <p><%= food.name %></p></td>
  <td> <p><%= food.measurement_unit %></p></td>
  <td> <p><%= food.price %></p></td>
  <td><%=  button_to "Delete Food", food_path(food.id), method: :delete,  data: { confirm: 'Are you sure you want to delete this topic?' } %></td>

</tr>

</table>

<%end%> 

app/views/foods/new.html.erb
<h1>New food</h1>


<div>
  <%= form_with(model: @food, url: foods_url, method: :post, local: true) do |form| %>
    <%= form.label(:name, "name") %>
    <%= form.text_field :name %>
     <%= form.label(:measurement_unit, "measurement unit?") %>
    <%= form.text_field :measurement_unit %>
    <%= form.label(:price, "price") %>
    <%= form.text_field :price %>
    <%= form.submit "Add food" %>
  <% end %>
</div>

app/views/inventories/index.html.erb
<h1>Inventory</h1>
<p>Please create your inventory</p>
<input type="text">
<button>Create</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
  <%= render partial: 'partials/header' %>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


    <%= yield %>
  </body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Recipe App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Inventory</a>
        </li>
        <li class="nav-item">
        <%= link_to 'Food' ,foods_path(current_user), class: "nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to 'My Recipies' ,recipes_path(current_user), class: "nav-link"%>
        </li>
        <li class="nav-item">
          <a class="nav-link">Public Recipies</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/recipe_foods/new.html.erb
<h1>add ingredients</h1>
<%= form_with(model: @recipe_food, url: recipe_recipe_foods_url, method: :post, local: true) do |form| %>
<%= form.select ( :food_id) , options_from_collection_for_select(@foods, "id", "name"), {}, { class: "border rounded" } %> 
  <%= form.label(:quantity, "quantity") %>
    <%= form.number_field :quantity%>
  <%= form.submit "Add ingredient" %>
<%end%>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

 <button><%= link_to ("Add a recipe"), new_recipe_path(@recipes)%></button>
<%@recipes.each do |recipe|%>
    <p><%= link_to (recipe.name), "/recipes/#{recipe.id}"%></p>
    <p><%=recipe.description%></p>
    <p><%=  button_to "Delete Recipe", "/users/:#{current_user.id}/recipes/#{recipe.id}", method: :delete,  data: { confirm: 'Are you sure you want to delete this topic?' } %></p>
<%end%> 

app/views/recipes/new.html.erb
<div>
  <%= form_with(model: @recipe, url: new_recipe_path, method: :post, local: true) do |form| %>
    <%= form.label(:name, "name") %>
    <%= form.text_field :name %>
     <%= form.label(:preparation_time, "Preparation time") %>
    <%= form.text_field :preparation_time %>
    <%= form.label(:cooking_time, "cooking time") %>
    <%= form.text_field :cooking_time %>
     <%= form.label(:description, "description") %>
    <%= form.text_area :description %>
    <%= form.check_box(:public) %>
<%= label_tag(:public, "Public") %>
    <%= form.submit "Add Recipe" %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<h1>Recipe <%= @recipe.id %></h1>
<p><%= @recipe.name %></p>
<p><%= @recipe.preparation_time %></p>
<p><%= @recipe.cooking_time %></p>


# <%@recipe.recipe_foods.each do |recipe_food|%>

#     <p><%= Food.find(recipe_food.food_id).name %></p>
#     <p><%= recipe_food.quantity %></p>

#     <% end %>
#     <p><%= @recipe.description %></p>
    <button><%= link_to ("Add ingredient"), new_recipe_recipe_food_path(@recipe.id)%></button>


    <table class="table">
  <thead>
    <tr>
 
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
    </tr>
  </thead>
  <tbody>
  <%@recipe.recipe_foods.each do |recipe_food|%>
    <tr>
    


      <td><%= Food.find(recipe_food.food_id).name %></td>
      <td><%= recipe_food.quantity %></td>
      <td>price</td>
     
      </tr>
      <% end %>
  </tbody>
</table>